[project]
name = "mcp-bugzilla"
version = "0.5.0"
description = "MCP server for Bugzilla"
readme = "README.md"
requires-python = "==3.13.*"

dependencies = [
    "fastmcp==2.12.5",
]

[project.optional-dependencies]
dev = [
    "uv",
]

[tool.setuptools]
py-modules = ["mcp_utils", "server"]
